export const features = {
  claims: {
    title: 'Claims',
    endpoint: 'claims',
    columns: [
      { key: 'claim_number', label: 'Claim #' },
      { key: 'type', label: 'Type' },
      { key: 'status', label: 'Status', render: 'badge' },
      { key: 'customer_name', label: 'Customer', fallback: 'customer_id' },
      { key: 'estimated_amount', label: 'Est. Amount', render: 'money' },
      { key: 'priority', label: 'Priority', render: 'badge' },
    ],
    formFields: [
      { key: 'claim_number', label: 'Claim Number', type: 'text' },
      { key: 'policy_id', label: 'Policy ID', type: 'number' },
      { key: 'customer_id', label: 'Customer ID', type: 'number' },
      { key: 'adjuster_id', label: 'Adjuster ID', type: 'number' },
      { key: 'type', label: 'Type', type: 'select', options: ['Auto Collision', 'Property Damage', 'Water Damage', 'Theft', 'Fire', 'Medical', 'Liability', 'Natural Disaster'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'incident_date', label: 'Incident Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'under_review', 'approved', 'denied', 'settled'] },
      { key: 'estimated_amount', label: 'Estimated Amount', type: 'number' },
      { key: 'approved_amount', label: 'Approved Amount', type: 'number' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'urgent'] },
    ],
    aiFeature: 'claim-analysis',
    aiFields: [
      { key: 'claim_id', label: 'Select Claim', type: 'dynamic-select', source: 'claims', optionLabel: (c) => `CLM #${c.claim_number} - ${c.type} (${c.status})`, autoFill: (claim) => ({ claim_number: claim.claim_number || '', claim_type: claim.type || '', description: claim.description || '', estimated_amount: claim.estimated_amount || '', status: claim.status || '' }) },
      { key: 'claim_number', label: 'Claim Number', type: 'text' },
      { key: 'claim_type', label: 'Claim Type', type: 'select', options: ['Auto Collision', 'Property Damage', 'Water Damage', 'Theft', 'Fire', 'Medical', 'Liability', 'Natural Disaster'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'estimated_amount', label: 'Estimated Amount', type: 'number' },
      { key: 'status', label: 'Current Status', type: 'select', options: ['open', 'under_review', 'approved', 'denied', 'settled'] },
    ],
    aiSamples: [
      { name: 'Complex Liability', data: { claim_number: 'CLM-SAMPLE-001', claim_type: 'Liability', description: 'Slip and fall at commercial property. Customer claims wet floor without signs caused broken hip. Witness statements contradictory. Claimant age 72 with pre-existing osteoporosis. Demanding $200,000.', estimated_amount: 200000, status: 'under_review' } },
      { name: 'Auto Multi-Vehicle', data: { claim_number: 'CLM-SAMPLE-002', claim_type: 'Auto Collision', description: '5-car pileup on highway during fog. Our insured was 3rd vehicle. Three other drivers claiming against insured. One hospitalized. Total exposure could exceed $500K.', estimated_amount: 125000, status: 'open' } },
    ],
    aiLabel: 'AI Claim Analysis',
  },

  policies: {
    title: 'Policies',
    endpoint: 'policies',
    columns: [
      { key: 'policy_number', label: 'Policy #' },
      { key: 'type', label: 'Type' },
      { key: 'customer_id', label: 'Customer ID' },
      { key: 'premium', label: 'Premium', render: 'money' },
      { key: 'coverage_limit', label: 'Coverage Limit', render: 'money' },
      { key: 'status', label: 'Status', render: 'badge' },
    ],
    formFields: [
      { key: 'policy_number', label: 'Policy Number', type: 'text' },
      { key: 'customer_id', label: 'Customer ID', type: 'number' },
      { key: 'type', label: 'Type', type: 'select', options: ['Auto', 'Home', 'Health', 'Life', 'Commercial'] },
      { key: 'premium', label: 'Premium', type: 'number' },
      { key: 'deductible', label: 'Deductible', type: 'number' },
      { key: 'coverage_limit', label: 'Coverage Limit', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'expired', 'cancelled', 'pending'] },
    ],
    aiFeature: 'policy-review',
    aiFields: [
      { key: 'policy_id', label: 'Select Policy', type: 'dynamic-select', source: 'policies', optionLabel: (p) => `POL #${p.policy_number} - ${p.type} ($${Number(p.premium||0).toLocaleString()}/yr)`, autoFill: (policy) => ({ policy_number: policy.policy_number || '', policy_type: policy.type || '', premium: policy.premium || '', coverage_limit: policy.coverage_limit || '', deductible: policy.deductible || '' }) },
      { key: 'policy_number', label: 'Policy Number', type: 'text' },
      { key: 'policy_type', label: 'Policy Type', type: 'select', options: ['Auto', 'Home', 'Health', 'Life', 'Commercial'] },
      { key: 'premium', label: 'Premium ($)', type: 'number' },
      { key: 'coverage_limit', label: 'Coverage Limit ($)', type: 'number' },
      { key: 'deductible', label: 'Deductible ($)', type: 'number' },
      { key: 'customer_info', label: 'Customer Info', type: 'textarea' },
    ],
    aiSamples: [
      { name: 'Underinsured Home', data: { policy_number: 'POL-SAMPLE-001', policy_type: 'Home', premium: 1800, coverage_limit: 200000, deductible: 2500, customer_info: 'Property value: $450,000. Home built 1985. Located in tornado alley. Coverage not updated in 8 years.' } },
      { name: 'Commercial Fleet', data: { policy_number: 'POL-SAMPLE-002', policy_type: 'Commercial', premium: 24000, coverage_limit: 1000000, deductible: 5000, customer_info: 'Delivery company, 12 vehicles, 3 at-fault accidents past year. No dash cameras.' } },
    ],
    aiLabel: 'AI Policy Review',
  },

  customers: {
    title: 'Customers',
    endpoint: 'customers',
    columns: [
      { key: 'first_name', label: 'First Name' },
      { key: 'last_name', label: 'Last Name' },
      { key: 'email', label: 'Email' },
      { key: 'phone', label: 'Phone' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
    ],
    formFields: [
      { key: 'first_name', label: 'First Name', type: 'text' },
      { key: 'last_name', label: 'Last Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'address', label: 'Address', type: 'textarea' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'state', label: 'State', type: 'text' },
      { key: 'zip', label: 'ZIP Code', type: 'text' },
      { key: 'date_of_birth', label: 'Date of Birth', type: 'date' },
    ],
    aiFeature: 'customer-analysis',
    aiFields: [
      { key: 'customer_id', label: 'Select Customer', type: 'dynamic-select', source: 'customers', optionLabel: (c) => `${c.first_name} ${c.last_name} - ${c.city || ''}, ${c.state || ''}`, autoFill: (cust) => ({ customer_name: `${cust.first_name} ${cust.last_name}` }) },
      { key: 'customer_name', label: 'Customer Name', type: 'text' },
      { key: 'total_policies', label: 'Total Policies', type: 'number' },
      { key: 'total_claims', label: 'Total Claims', type: 'number' },
      { key: 'claim_history', label: 'Claim History Summary', type: 'textarea' },
    ],
    aiSamples: [
      { name: 'High-Value Customer', data: { customer_name: 'Patricia Wellington', total_policies: 5, total_claims: 1, claim_history: 'Customer since 2010. 5 policies, $18,500 annual premiums. Only 1 minor claim in 14 years. Credit score 810. Referred 4 customers.' } },
      { name: 'Frequent Claimant', data: { customer_name: 'Marcus Johnson', total_policies: 2, total_claims: 7, claim_history: 'Customer since 2019. 7 claims in 5 years: 3 auto (2 at-fault), 2 theft, 1 water, 1 liability. Total paid: $89K. Loss ratio: 556%.' } },
    ],
    aiLabel: 'AI Customer Analysis',
  },

  adjusters: {
    title: 'Adjusters',
    endpoint: 'adjusters',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'specialization', label: 'Specialization' },
      { key: 'experience_years', label: 'Experience (yrs)' },
      { key: 'status', label: 'Status', render: 'badge' },
      { key: 'rating', label: 'Rating' },
    ],
    formFields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'specialization', label: 'Specialization', type: 'select', options: ['Auto', 'Property', 'Health', 'Life', 'Commercial', 'Marine', 'Workers Comp', 'General'] },
      { key: 'license_number', label: 'License Number', type: 'text' },
      { key: 'experience_years', label: 'Experience (Years)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'on_leave'] },
      { key: 'rating', label: 'Rating', type: 'number' },
    ],
    aiFeature: 'adjuster-performance',
    aiFields: [
      { key: 'adjuster_id', label: 'Select Adjuster', type: 'dynamic-select', source: 'adjusters', optionLabel: (a) => `${a.name} - ${a.specialization} (${a.experience_years}yr)`, autoFill: (adj) => ({ adjuster_name: adj.name || '', specialization: adj.specialization || '', experience_years: adj.experience_years || '' }) },
      { key: 'adjuster_name', label: 'Adjuster Name', type: 'text' },
      { key: 'specialization', label: 'Specialization', type: 'select', options: ['Auto', 'Property', 'Health', 'Life', 'Commercial', 'Marine', 'Workers Comp', 'General'] },
      { key: 'experience_years', label: 'Experience (Years)', type: 'number' },
      { key: 'total_claims_handled', label: 'Total Claims Handled', type: 'number' },
      { key: 'average_resolution_time', label: 'Avg Resolution (Days)', type: 'number' },
    ],
    aiSamples: [
      { name: 'Top Performer', data: { adjuster_name: 'Sarah Mitchell', specialization: 'Auto', experience_years: 12, total_claims_handled: 847, average_resolution_time: 14 } },
      { name: 'New Adjuster', data: { adjuster_name: 'Kevin Park', specialization: 'Property', experience_years: 2, total_claims_handled: 45, average_resolution_time: 32 } },
    ],
    aiLabel: 'AI Performance Analysis',
  },

  fraudDetection: {
    title: 'Fraud Detection',
    endpoint: 'fraud-alerts',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'claim_id', label: 'Claim ID' },
      { key: 'risk_score', label: 'Risk Score' },
      { key: 'status', label: 'Status', render: 'badge' },
      { key: 'created_at', label: 'Created', render: 'date' },
    ],
    formFields: [
      { key: 'claim_id', label: 'Claim ID', type: 'number' },
      { key: 'risk_score', label: 'Risk Score', type: 'number' },
      { key: 'indicators', label: 'Indicators', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'investigating', 'confirmed', 'cleared'] },
      { key: 'reviewed_by', label: 'Reviewed By', type: 'text' },
    ],
    aiFeature: 'fraud-detection',
    aiFields: [
      { key: 'claim_id', label: 'Select Claim', type: 'dynamic-select', source: 'claims', optionLabel: (c) => `CLM #${c.claim_number} - ${c.type} ($${Number(c.estimated_amount||0).toLocaleString()})`, autoFill: (claim) => ({ claim_description: claim.description || '', claim_amount: claim.estimated_amount || '', claim_type: claim.type || '' }) },
      { key: 'claim_description', label: 'Claim Description', type: 'textarea' },
      { key: 'claim_amount', label: 'Claim Amount', type: 'number' },
      { key: 'claim_type', label: 'Claim Type', type: 'select', options: ['Auto', 'Property', 'Health', 'Life', 'Commercial'] },
    ],
    aiSamples: [
      { name: 'Suspicious Auto', data: { claim_description: 'Vehicle stolen from locked garage. No forced entry. Found burned 50 miles away. Policy increased 2 weeks prior. 3 previous theft claims in 5 years.', claim_amount: 75000, claim_type: 'Auto' } },
      { name: 'Excessive Medical', data: { claim_description: 'Patient claims workplace injury. 8 months treatment for minor sprain. Bills exceed typical costs by 300%. Multiple specialist visits seem unnecessary.', claim_amount: 45000, claim_type: 'Health' } },
    ],
    aiLabel: 'Run AI Fraud Detection',
  },

  damageAssessment: {
    title: 'Damage Assessment',
    endpoint: 'damage-assessments',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'claim_id', label: 'Claim ID' },
      { key: 'damage_type', label: 'Damage Type' },
      { key: 'severity', label: 'Severity', render: 'badge' },
      { key: 'estimated_cost', label: 'Est. Cost', render: 'money' },
      { key: 'created_at', label: 'Created', render: 'date' },
    ],
    formFields: [
      { key: 'claim_id', label: 'Claim ID', type: 'number' },
      { key: 'damage_type', label: 'Damage Type', type: 'text' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['minor', 'moderate', 'severe', 'catastrophic'] },
      { key: 'estimated_cost', label: 'Estimated Cost', type: 'number' },
      { key: 'repair_timeline', label: 'Repair Timeline', type: 'text' },
      { key: 'photos_reviewed', label: 'Photos Reviewed', type: 'number' },
    ],
    aiFeature: 'damage-assessment',
    aiFields: [
      { key: 'claim_id', label: 'Select Claim', type: 'dynamic-select', source: 'claims', optionLabel: (c) => `CLM #${c.claim_number} - ${c.type}`, autoFill: (claim) => ({ description: claim.description || '', location: claim.location || '' }) },
      { key: 'description', label: 'Damage Description', type: 'textarea' },
      { key: 'damage_type', label: 'Damage Type', type: 'select', options: ['Structural', 'Vehicle', 'Water', 'Fire', 'Electrical', 'Roof', 'Foundation', 'Interior'] },
      { key: 'location', label: 'Location', type: 'text' },
    ],
    aiSamples: [
      { name: 'House Fire', data: { description: 'Kitchen fire spread to dining and living area. Cabinets, appliances, flooring destroyed. Smoke damage throughout first floor. Roof partially collapsed.', damage_type: 'Fire', location: '456 Oak Drive, Denver, CO' } },
      { name: 'Storm Roof', data: { description: 'Hailstorm caused missing and cracked shingles. Gutters dented. Two skylights cracked. Water infiltration into attic.', damage_type: 'Roof', location: '789 Maple St, Oklahoma City, OK' } },
    ],
    aiLabel: 'Run AI Damage Assessment',
  },

  riskAssessment: {
    title: 'Risk Assessment',
    endpoint: 'risk-assessments',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'policy_id', label: 'Policy ID' },
      { key: 'customer_name', label: 'Customer' },
      { key: 'risk_level', label: 'Risk Level', render: 'badge' },
      { key: 'risk_score', label: 'Risk Score' },
      { key: 'created_at', label: 'Created', render: 'date' },
    ],
    formFields: [
      { key: 'policy_id', label: 'Policy ID', type: 'number' },
      { key: 'customer_name', label: 'Customer Name', type: 'text' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'risk_score', label: 'Risk Score', type: 'number' },
      { key: 'factors', label: 'Factors', type: 'textarea' },
      { key: 'recommendation', label: 'Recommendation', type: 'textarea' },
    ],
    aiFeature: 'risk-assessment',
    aiFields: [
      { key: 'policy_id', label: 'Select Policy', type: 'dynamic-select', source: 'policies', optionLabel: (p) => `POL #${p.policy_number} - ${p.type} ($${Number(p.coverage_limit||0).toLocaleString()})`, autoFill: (policy) => ({ policy_type: policy.type || '', coverage_amount: policy.coverage_limit || '' }) },
      { key: 'customer_info', label: 'Customer Info', type: 'textarea' },
      { key: 'policy_type', label: 'Policy Type', type: 'select', options: ['Auto', 'Home', 'Health', 'Life', 'Commercial'] },
      { key: 'coverage_amount', label: 'Coverage Amount', type: 'number' },
    ],
    aiSamples: [
      { name: 'Hurricane Zone Home', data: { customer_info: 'Homeowner age 55, $2.5M waterfront property in hurricane zone. 2 water damage claims in 3 years. Home built 1998. No security system.', policy_type: 'Home', coverage_amount: 2500000 } },
      { name: 'Young Driver', data: { customer_info: 'New driver age 19, male. Sports car 2024 Mustang GT. No driving history. Urban area, high theft. 45-mile daily commute.', policy_type: 'Auto', coverage_amount: 100000 } },
    ],
    aiLabel: 'Run AI Risk Assessment',
  },

  settlementRecommendation: {
    title: 'Settlement Recommendation',
    endpoint: 'settlements',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'claim_id', label: 'Claim ID' },
      { key: 'claim_number', label: 'Claim #' },
      { key: 'recommended_amount', label: 'Recommended', render: 'money' },
      { key: 'final_amount', label: 'Final Amount', render: 'money' },
      { key: 'status', label: 'Status', render: 'badge' },
      { key: 'created_at', label: 'Created', render: 'date' },
    ],
    formFields: [
      { key: 'claim_id', label: 'Claim ID', type: 'number' },
      { key: 'claim_number', label: 'Claim Number', type: 'text' },
      { key: 'recommended_amount', label: 'Recommended Amount', type: 'number' },
      { key: 'final_amount', label: 'Final Amount', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'approved', 'paid', 'rejected'] },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
    ],
    aiFeature: 'settlement-recommendation',
    aiFields: [
      { key: 'claim_id', label: 'Select Claim', type: 'dynamic-select', source: 'claims', optionLabel: (c) => `CLM #${c.claim_number} - ${c.type} ($${Number(c.estimated_amount||0).toLocaleString()})`, autoFill: (claim) => ({ claim_description: claim.description || '', claim_amount: claim.estimated_amount || '' }) },
      { key: 'claim_description', label: 'Claim Description', type: 'textarea' },
      { key: 'claim_amount', label: 'Claim Amount', type: 'number' },
      { key: 'policy_coverage', label: 'Policy Coverage', type: 'number' },
      { key: 'damage_assessment', label: 'Damage Assessment', type: 'textarea' },
    ],
    aiSamples: [
      { name: 'Auto Total Loss', data: { claim_description: '2021 Toyota Camry totaled. Other driver at fault. Fair market value $28,000. Rental $1,200. Whiplash medical $3,500.', claim_amount: 32700, policy_coverage: 100000, damage_assessment: 'Total loss confirmed. FMV $28K. Medical expenses reasonable.' } },
      { name: 'Water Damage', data: { claim_description: 'Burst pipe flooded finished basement. Hardwood warped 800 sq ft. Drywall 3 rooms. Home theater destroyed.', claim_amount: 45000, policy_coverage: 500000, damage_assessment: 'Flooring $12K, Drywall $5K, Electronics $8K, Furniture $6K, Labor $14K.' } },
    ],
    aiLabel: 'Run AI Settlement Recommendation',
  },

  documentAnalysis: {
    title: 'Document Analysis',
    endpoint: 'documents',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'claim_id', label: 'Claim ID' },
      { key: 'document_type', label: 'Document Type' },
      { key: 'file_name', label: 'File Name' },
      { key: 'status', label: 'Status', render: 'badge' },
      { key: 'created_at', label: 'Created', render: 'date' },
    ],
    formFields: [
      { key: 'claim_id', label: 'Claim ID', type: 'number' },
      { key: 'document_type', label: 'Document Type', type: 'select', options: ['Police Report', 'Medical Report', 'Repair Estimate', 'Photos', 'Insurance Form', 'Witness Statement', 'Appraisal', 'Correspondence'] },
      { key: 'file_name', label: 'File Name', type: 'text' },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'analyzed', 'reviewed'] },
    ],
    aiFeature: 'document-analysis',
    aiFields: [
      { key: 'document_id', label: 'Select Document', type: 'dynamic-select', source: 'documents', optionLabel: (d) => `DOC #${d.id} - ${d.document_type} (${d.file_name})`, autoFill: (doc) => ({ document_text: doc.content || '', document_type: doc.document_type || '' }) },
      { key: 'document_text', label: 'Document Text', type: 'textarea' },
      { key: 'document_type', label: 'Document Type', type: 'select', options: ['Police Report', 'Medical Report', 'Repair Estimate', 'Photos', 'Insurance Form', 'Witness Statement'] },
    ],
    aiSamples: [
      { name: 'Police Report', data: { document_text: 'INCIDENT REPORT #2024-5678. Date: March 15, 2024. Vehicle 1 (2021 Honda Accord) was struck by Vehicle 2 (2019 Ford F-150) which ran a red light. Driver of V1 transported to hospital with neck pain. Two witnesses confirmed V2 ran the red light. Estimated damage V1: $15,000.', document_type: 'Police Report' } },
      { name: 'Repair Estimate', data: { document_text: 'AUTO REPAIR ESTIMATE - Premier Auto Body. 2021 Honda Accord. Driver side door replace: $1,850. Fender replace: $680. Mirror: $420. Paint 3 panels: $1,200. Frame straightening: $2,400. Labor 32hrs: $2,720. TOTAL: $10,635. Est. 12-15 business days.', document_type: 'Repair Estimate' } },
    ],
    aiLabel: 'Run AI Document Analysis',
  },

  policyCoverage: {
    title: 'Policy Coverage Analysis',
    endpoint: 'policies',
    columns: [
      { key: 'policy_number', label: 'Policy #' },
      { key: 'type', label: 'Type' },
      { key: 'premium', label: 'Premium', render: 'money' },
      { key: 'coverage_limit', label: 'Coverage Limit', render: 'money' },
      { key: 'status', label: 'Status', render: 'badge' },
    ],
    formFields: [
      { key: 'policy_number', label: 'Policy Number', type: 'text' },
      { key: 'customer_id', label: 'Customer ID', type: 'number' },
      { key: 'type', label: 'Type', type: 'select', options: ['Auto', 'Home', 'Health', 'Life', 'Commercial'] },
      { key: 'premium', label: 'Premium', type: 'number' },
      { key: 'deductible', label: 'Deductible', type: 'number' },
      { key: 'coverage_limit', label: 'Coverage Limit', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'expired', 'cancelled', 'pending'] },
    ],
    aiFeature: 'policy-coverage',
    aiFields: [
      { key: 'policy_id', label: 'Select Policy', type: 'dynamic-select', source: 'policies', optionLabel: (p) => `POL #${p.policy_number} - ${p.type} ($${Number(p.coverage_limit||0).toLocaleString()})`, autoFill: (policy) => ({ policy_type: policy.type || '', coverage_details: `Type: ${policy.type}, Premium: $${policy.premium}, Deductible: $${policy.deductible}, Limit: $${policy.coverage_limit}` }) },
      { key: 'policy_type', label: 'Policy Type', type: 'select', options: ['Auto', 'Home', 'Health', 'Life', 'Commercial'] },
      { key: 'coverage_details', label: 'Coverage Details', type: 'textarea' },
      { key: 'claim_description', label: 'Claim Description', type: 'textarea' },
    ],
    aiSamples: [
      { name: 'Flood (Home Policy)', data: { policy_type: 'Home', coverage_details: 'Standard HO-3. Dwelling: $350K. Personal Property: $175K. Deductible: $1K. No flood rider.', claim_description: 'River overflow flooded first floor. 6 inches standing water for 48 hours. Damage to flooring, walls, appliances. Est. loss: $85,000.' } },
      { name: 'Rental Car (Auto)', data: { policy_type: 'Auto', coverage_details: 'Full coverage. Liability 100/300/100. Collision $500 ded. NO rental reimbursement. NO gap coverage.', claim_description: 'Vehicle rear-ended, needs 3 weeks repair. Driver requesting rental at $45/day plus $2,000 lost wages.' } },
    ],
    aiLabel: 'Run AI Coverage Analysis',
  },

  customerSentiment: {
    title: 'Customer Sentiment',
    endpoint: 'communications',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'customer_name', label: 'Customer' },
      { key: 'channel', label: 'Channel' },
      { key: 'subject', label: 'Subject' },
      { key: 'sentiment', label: 'Sentiment', render: 'badge' },
      { key: 'sentiment_score', label: 'Score' },
      { key: 'created_at', label: 'Created', render: 'date' },
    ],
    formFields: [
      { key: 'claim_id', label: 'Claim ID', type: 'number' },
      { key: 'customer_id', label: 'Customer ID', type: 'number' },
      { key: 'customer_name', label: 'Customer Name', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'select', options: ['email', 'phone', 'chat', 'letter', 'social_media'] },
      { key: 'subject', label: 'Subject', type: 'text' },
      { key: 'message', label: 'Message', type: 'textarea' },
      { key: 'sentiment', label: 'Sentiment', type: 'select', options: ['positive', 'neutral', 'negative', 'urgent'] },
      { key: 'sentiment_score', label: 'Sentiment Score', type: 'number' },
    ],
    aiFeature: 'customer-sentiment',
    aiFields: [
      { key: 'customer_id', label: 'Select Customer', type: 'dynamic-select', source: 'customers', optionLabel: (c) => `${c.first_name} ${c.last_name} (${c.email || 'No email'})`, autoFill: (cust) => ({ customer_name: `${cust.first_name} ${cust.last_name}` }) },
      { key: 'customer_name', label: 'Customer Name', type: 'text' },
      { key: 'message', label: 'Message', type: 'textarea' },
      { key: 'channel', label: 'Channel', type: 'select', options: ['email', 'phone', 'chat', 'letter'] },
    ],
    aiSamples: [
      { name: 'Angry Customer', data: { customer_name: 'Robert Thompson', message: 'This is unacceptable! Filed claim THREE WEEKS ago, nobody called back. Paying out of pocket for rental. 12-year loyal customer. Want a supervisor or I am switching companies!', channel: 'email' } },
      { name: 'Happy Customer', data: { customer_name: 'Lisa Park', message: 'Want to thank your team, especially adjuster Michael. Professional, kept me informed. Fair settlement in 10 days. Will recommend you to others.', channel: 'email' } },
    ],
    aiLabel: 'Run AI Sentiment Analysis',
  },

  claimsForecasting: {
    title: 'Claims Forecasting',
    endpoint: null,
    columns: [],
    formFields: [],
    aiFeature: 'claims-forecasting',
    aiFields: [
      { key: 'claim_type', label: 'Claim Type', type: 'select', options: ['Auto', 'Property', 'Health', 'Life', 'Commercial', 'All'] },
      { key: 'region', label: 'Region', type: 'select', options: ['Northeast', 'Southeast', 'Midwest', 'Southwest', 'West', 'National'] },
      { key: 'time_period', label: 'Time Period', type: 'select', options: ['Next Month', 'Next Quarter', 'Next 6 Months', 'Next Year'] },
      { key: 'historical_context', label: 'Historical Context', type: 'textarea' },
    ],
    aiLabel: 'Run AI Claims Forecast',
    aiOnly: true,
  },

  payments: {
    title: 'Payments',
    endpoint: 'payments',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'claim_number', label: 'Claim #' },
      { key: 'amount', label: 'Amount', render: 'money' },
      { key: 'payment_method', label: 'Method' },
      { key: 'payment_date', label: 'Date', render: 'date' },
      { key: 'status', label: 'Status', render: 'badge' },
      { key: 'payee_name', label: 'Payee' },
    ],
    formFields: [
      { key: 'claim_id', label: 'Claim ID', type: 'number' },
      { key: 'claim_number', label: 'Claim Number', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'payment_method', label: 'Payment Method', type: 'select', options: ['Check', 'ACH', 'Wire Transfer', 'Direct Deposit'] },
      { key: 'payment_date', label: 'Payment Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'processing', 'completed', 'failed', 'refunded'] },
      { key: 'reference_number', label: 'Reference Number', type: 'text' },
      { key: 'payee_name', label: 'Payee Name', type: 'text' },
    ],
    aiFeature: 'payment-analysis',
    aiFields: [
      { key: 'claim_id', label: 'Select Related Claim', type: 'dynamic-select', source: 'claims', optionLabel: (c) => `CLM #${c.claim_number} - ${c.type}`, autoFill: (claim) => ({ claim_info: `Claim #${claim.claim_number}, Type: ${claim.type}, Amount: $${claim.estimated_amount}, Status: ${claim.status}` }) },
      { key: 'payment_details', label: 'Payment Details', type: 'textarea' },
      { key: 'total_amount', label: 'Total Amount ($)', type: 'number' },
      { key: 'payment_method', label: 'Payment Method', type: 'select', options: ['Check', 'ACH', 'Wire Transfer', 'Direct Deposit'] },
      { key: 'claim_info', label: 'Related Claim Info', type: 'textarea' },
    ],
    aiSamples: [
      { name: 'Suspicious Wire', data: { payment_details: 'Wire transfer $95K to overseas account. Payee name mismatch. Rush request. Claim filed 5 days ago, investigation pending.', total_amount: 95000, payment_method: 'Wire Transfer', claim_info: 'Commercial claim filed 5 days ago. No adjuster assigned. Investigation pending.' } },
      { name: 'Normal Payment', data: { payment_details: 'Standard ACH for settled auto claim. Payee matches policyholder. All docs verified.', total_amount: 12500, payment_method: 'ACH', claim_info: 'Auto claim CLM-2024-008. Filed 45 days ago. Investigation complete. Adjuster approved.' } },
    ],
    aiLabel: 'AI Payment Analysis',
  },

  auditLog: {
    title: 'Audit Log',
    endpoint: 'audit-log',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'user_name', label: 'User' },
      { key: 'action', label: 'Action' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'created_at', label: 'Timestamp', render: 'date' },
    ],
    formFields: [
      { key: 'user_name', label: 'User Name', type: 'text' },
      { key: 'action', label: 'Action', type: 'text' },
      { key: 'entity_type', label: 'Entity Type', type: 'text' },
      { key: 'entity_id', label: 'Entity ID', type: 'number' },
      { key: 'details', label: 'Details', type: 'textarea' },
      { key: 'ip_address', label: 'IP Address', type: 'text' },
    ],
    readOnly: true,
    aiFeature: 'audit-analysis',
    aiFields: [
      { key: 'audit_entries', label: 'Audit Entries Summary', type: 'textarea' },
      { key: 'time_period', label: 'Time Period', type: 'select', options: ['Last 24 Hours', 'Last Week', 'Last Month', 'Last Quarter'] },
      { key: 'entity_type', label: 'Entity Type', type: 'select', options: ['All', 'Claims', 'Policies', 'Customers', 'Payments', 'Users'] },
    ],
    aiSamples: [
      { name: 'After-Hours Activity', data: { audit_entries: 'User john.smith accessed 47 customer records 11PM-3AM. Modified 12 claim amounts. Exported customer list with SSNs. Changed 3 payment destinations.', time_period: 'Last 24 Hours', entity_type: 'All' } },
      { name: 'Monthly Review', data: { audit_entries: 'Total actions: 15,234. Claims modified: 892. Payments processed: 334. Failed logins: 23. Admin actions: 89. Data exports: 12.', time_period: 'Last Month', entity_type: 'All' } },
    ],
    aiLabel: 'AI Audit Analysis',
  },
}
